[package]
name = "zakariyalaswad/swappz"
version = "0.1.0"
description = "SkillSwap static build for Wasmer Edge"

[dependencies]
"sharrattj/static-web-server" = "1"

[fs]
public = "dist/SkillSwap/browser"
